/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeBets"
      | "addAllowedToken"
      | "allowedTokens"
      | "betCounter"
      | "bets"
      | "cancelBet"
      | "currentPrices"
      | "feePool"
      | "getActiveBetsCount"
      | "getAllowedTokens"
      | "getBet"
      | "getPrice"
      | "getUserBets"
      | "lastPriceUpdate"
      | "maxBetAmount"
      | "maxDuration"
      | "minBetAmount"
      | "minDuration"
      | "owner"
      | "placeBet"
      | "priceOracle"
      | "resolveBet"
      | "setFeePool"
      | "setPriceOracle"
      | "tokenList"
      | "totalBets"
      | "totalVolume"
      | "updateLimits"
      | "updatePrice"
      | "updatePrices"
      | "userBets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetPlaced"
      | "BetResolved"
      | "PriceUpdated"
      | "TokenAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeBets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAllowedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "betCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bets", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "cancelBet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentPrices",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "feePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getActiveBetsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPriceUpdate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxBetAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minBetAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minDuration",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [AddressLike, BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveBet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeePool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "totalBets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateLimits",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrice",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrices",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "userBets",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "activeBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addAllowedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "betCounter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveBetsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPriceUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxBetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minBetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolveBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFeePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userBets", data: BytesLike): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    betId: BigNumberish,
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    predictUp: boolean,
    duration: BigNumberish
  ];
  export type OutputTuple = [
    betId: bigint,
    user: string,
    token: string,
    amount: bigint,
    predictUp: boolean,
    duration: bigint
  ];
  export interface OutputObject {
    betId: bigint;
    user: string;
    token: string;
    amount: bigint;
    predictUp: boolean;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetResolvedEvent {
  export type InputTuple = [
    betId: BigNumberish,
    user: AddressLike,
    won: boolean,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    betId: bigint,
    user: string,
    won: boolean,
    reward: bigint
  ];
  export interface OutputObject {
    betId: bigint;
    user: string;
    won: boolean;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    token: AddressLike,
    price: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [token: string, price: bigint, timestamp: bigint];
  export interface OutputObject {
    token: string;
    price: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenAddedEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeBets: TypedContractMethod<[], [bigint], "view">;

  addAllowedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  allowedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  betCounter: TypedContractMethod<[], [bigint], "view">;

  bets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        user: string;
        token: string;
        amount: bigint;
        initialPrice: bigint;
        finalPrice: bigint;
        startTime: bigint;
        endTime: bigint;
        predictUp: boolean;
        status: bigint;
      }
    ],
    "view"
  >;

  cancelBet: TypedContractMethod<[betId: BigNumberish], [void], "nonpayable">;

  currentPrices: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  feePool: TypedContractMethod<[], [string], "view">;

  getActiveBetsCount: TypedContractMethod<[], [bigint], "view">;

  getAllowedTokens: TypedContractMethod<[], [string[]], "view">;

  getBet: TypedContractMethod<
    [betId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        user: string;
        token: string;
        amount: bigint;
        initialPrice: bigint;
        finalPrice: bigint;
        startTime: bigint;
        endTime: bigint;
        predictUp: boolean;
        status: bigint;
      }
    ],
    "view"
  >;

  getPrice: TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { price: bigint; lastUpdate: bigint }],
    "view"
  >;

  getUserBets: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  lastPriceUpdate: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  maxBetAmount: TypedContractMethod<[], [bigint], "view">;

  maxDuration: TypedContractMethod<[], [bigint], "view">;

  minBetAmount: TypedContractMethod<[], [bigint], "view">;

  minDuration: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  placeBet: TypedContractMethod<
    [
      token: AddressLike,
      amount: BigNumberish,
      predictUp: boolean,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  priceOracle: TypedContractMethod<[], [string], "view">;

  resolveBet: TypedContractMethod<[betId: BigNumberish], [void], "nonpayable">;

  setFeePool: TypedContractMethod<
    [_feePool: AddressLike],
    [void],
    "nonpayable"
  >;

  setPriceOracle: TypedContractMethod<
    [_oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  tokenList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  totalBets: TypedContractMethod<[], [bigint], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  updateLimits: TypedContractMethod<
    [
      _minBet: BigNumberish,
      _maxBet: BigNumberish,
      _minDuration: BigNumberish,
      _maxDuration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updatePrice: TypedContractMethod<
    [token: AddressLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  updatePrices: TypedContractMethod<
    [tokens: AddressLike[], prices: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  userBets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeBets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addAllowedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "betCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        user: string;
        token: string;
        amount: bigint;
        initialPrice: bigint;
        finalPrice: bigint;
        startTime: bigint;
        endTime: bigint;
        predictUp: boolean;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelBet"
  ): TypedContractMethod<[betId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentPrices"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "feePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveBetsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllowedTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBet"
  ): TypedContractMethod<
    [betId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        user: string;
        token: string;
        amount: bigint;
        initialPrice: bigint;
        finalPrice: bigint;
        startTime: bigint;
        endTime: bigint;
        predictUp: boolean;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { price: bigint; lastUpdate: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBets"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "lastPriceUpdate"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxBetAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minBetAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [
      token: AddressLike,
      amount: BigNumberish,
      predictUp: boolean,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveBet"
  ): TypedContractMethod<[betId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeePool"
  ): TypedContractMethod<[_feePool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceOracle"
  ): TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalBets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateLimits"
  ): TypedContractMethod<
    [
      _minBet: BigNumberish,
      _maxBet: BigNumberish,
      _minDuration: BigNumberish,
      _maxDuration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePrice"
  ): TypedContractMethod<
    [token: AddressLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePrices"
  ): TypedContractMethod<
    [tokens: AddressLike[], prices: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userBets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "BetResolved"
  ): TypedContractEvent<
    BetResolvedEvent.InputTuple,
    BetResolvedEvent.OutputTuple,
    BetResolvedEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenAdded"
  ): TypedContractEvent<
    TokenAddedEvent.InputTuple,
    TokenAddedEvent.OutputTuple,
    TokenAddedEvent.OutputObject
  >;

  filters: {
    "BetPlaced(uint256,address,address,uint256,bool,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "BetResolved(uint256,address,bool,uint256)": TypedContractEvent<
      BetResolvedEvent.InputTuple,
      BetResolvedEvent.OutputTuple,
      BetResolvedEvent.OutputObject
    >;
    BetResolved: TypedContractEvent<
      BetResolvedEvent.InputTuple,
      BetResolvedEvent.OutputTuple,
      BetResolvedEvent.OutputObject
    >;

    "PriceUpdated(address,uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "TokenAdded(address)": TypedContractEvent<
      TokenAddedEvent.InputTuple,
      TokenAddedEvent.OutputTuple,
      TokenAddedEvent.OutputObject
    >;
    TokenAdded: TypedContractEvent<
      TokenAddedEvent.InputTuple,
      TokenAddedEvent.OutputTuple,
      TokenAddedEvent.OutputObject
    >;
  };
}
